### ISSUE TITLE
No answer from server

### ISSUE THREAD

**Issue by marvingrieger** [Haba1234/homebridge-iobroker#1]
Hello,

first of all: Thanks for this plugin - I was really missing this kind of link between ioBroker and Homebridge.

When trying to get the plugin, I'm stumbling over the following error, which crashes the homebridge-server during the startup:

```
/usr/lib/node_modules/homebridge-iobroker/lib/conn.js:223
                        this.platform.error('No answer from server')
                                      ^

TypeError: Cannot read property 'error' of undefined
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-iobroker/lib/conn.js:223:39)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

Seems like a timeout occurs during the connection process. In the log of ioBroker, I can see that the basic connection between homebridge and the socketio-adapter works:

```
socketio.0 | 2018-07-29 21:28:43.842 | info | <==Disconnect system.user.admin from ::ffff:127.0.0.1 homebridge
socketio.0 | 2018-07-29 21:28:39.828 | info | ==>Connected system.user.admin from ::ffff:127.0.0.1
```

Do you have any idea what the problem might be?

Best regards

**Comment by g88704** [comment]
Hi Marvin,

could you find a solution for the connection/startup issue?

Thanks and Regards
